config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact'    => 'static_pages#contact'
  get 'chef'    => 'static_pages#chef'
  get 'menu'    => 'static_pages#menu'
  get 'location'    => 'static_pages#location'
  get 'reservations'    => 'static_pages#reservations'
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email,
    :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      # TODO save data
      # TODO send message
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def menu
  end
  
  def reservations
  end
  
  def location
  end
  
  def chef
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<%# Navigation links %>
<%= render 'layouts/navigation' %>

app/views/layouts/_meta.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://maps.googleapis.com/maps/api/js"></script>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

app/views/layouts/_navigation.html.erb
<nav class="navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle show-mobile collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
          <i class="fa fa-bars fa-3x"></i>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%# renders the navigation links %>
          <%= render 'layouts/navlinks' %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/_navlinks.html.erb
<li><%= link_to "Home",    root_path %></li>
<li><%= link_to "Menu",    menu_path %></li>
<li><%= link_to "Reservations",   reservations_path %></li>
<li><%= link_to "Location & Times",    location_path %></li>
<li><%= link_to "Chef",    chef_path %></li>
<li><%= link_to "Contact",    contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiltshire Pub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/meta' %>
</head>
<body class="body">
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/static_pages/chef.html.erb
<!-- Large banner card -->
<div id="menuCard" class="smallCard">
  <div>
    <a href="#">MEET WILTSHIRE'S WORLD CLASS CHEF</a>
  </div>
</div>

<main class="menu" id="chefMenu">
  <h2>Meet Marty McFly, Wiltshire's chef.</h2>
  <%= image_tag('chef.jpg', :class => 'chefPic') %>
  <p>Marty has been cooking for Wiltshire since 1965.</p>
  <p>Studying the culinary arts at Rhode School of Cuisine at Dar Liqama, <br> Marty knows how to get your meal just right.</p>
</main>

app/views/static_pages/contact.html.erb
<!-- Large banner card -->
<div id="menuCard" class="smallCard">
  <div>
    <a href="#">CONTACT US</a>
  </div>
</div>

<main class="menu" id="contactMenu">
  <form class="contactForm">
    <div class="formContainer">
      <div class="contactName">
        <p>Enter your full name.</p>
        <input type="text" name="fname" placeholder="Enter Your Full Name">
      </div>
      <div class="contactEmail">
        <p>Enter your email address.</p>
        <input type="email" name="email" placeholder="Enter Your Email Address">
      </div>
      <div class="contactDetails">
        <p>Enter your message here:</p>
        <textarea placeholder="Your message" rows="4" cols="50"></textarea>
      </div>
      <div class="submitContact" type="submit">Submit</div>
    </div>
  </form> 
</main>

<div class="contactConfirm">
  <h2>Thank you for submitting your message.</h2>
</div>

app/views/static_pages/home.html.erb
<div class="card">
  <!-- Title picture with logo words over top -->
  <div class="titleCard">
    <h1 class="titleCard-logo">Welcome To Wiltshire Pub</h1>
  </div>
  <!-- Bottom portion of the logo where text is displayed -->
  <div class="title-bottom">
    <p>The finest pub England has to offer</p>
  </div>
  <div class="title-bottom">
    <%# Rails links to the menu %>
    <%= link_to menu_path do %>
      Click here to view our menu      
      <i class="fa fa-chevron-right"></i>
    <% end %>  
  </div>
</div>

<!-- Individual card with text on the right -->
<div class="smallCard">
  <%= image_tag('londonpub1.JPG') %>
  <div class="card-right">
    <p>Located in the heart of England, Wiltshire is well worth the trip.</p>
    <%= link_to location_path do %>
      Click here for directions     
      <i class="fa fa-chevron-right"></i>
    <% end %> 
  </div>
</div>

<!-- Individual card with no picture -->
<div id="card2" class="smallCard">
  <div class="card-right">
    <p>Wiltshire Pub is home to the world renound chef, Marty McFly.</p>
    <%= link_to chef_path do %>
      You can meet him here       
      <i class="fa fa-chevron-right"></i>
    <% end %> 
  </div>
</div>

<!-- Individual card with text on the left -->
<div id="card3" class="smallCard">
  <div class="card-left">
    <p>Wiltshire pub is always open, but private rooms require reservations.</p>
    <%= link_to reservations_path do %>
      Book a room today         
      <i class="fa fa-chevron-right"></i>
    <% end %> 
  </div>
  <%= image_tag('londonpub2.jpg') %>
</div>

<!-- Individual card with text on the right -->
<div id="card4" class="smallCard">
  <div>
    <%= link_to contact_path do %>
      Need anything? Contact us here 
      <i class="fa fa-chevron-right"></i>
    <% end %> 
  </div>
</div>

app/views/static_pages/location.html.erb
<!-- Large banner card -->
<div id="menuCard" class="smallCard">
  <div>
    <a href="#">VIEW WILTSHIRE'S LOCATION AND HOURS</a>
  </div>
</div>

<!-- Menu With location info and hours.. also google maps -->
<main class="menu" id="locationMenu">
  <div id="map-canvas"></div>
  <div class="locationInfo">
    <h4>Hours:</h4>
    <p>Monday-Thursday: 12:00-24:00</p>
    <p>Friday-Sunday:   12:00-04:00</p>
    <br>
    <h4>Address:</h4>
    <p>210 Church Street, North Lavington,</p>
    <p>Wiltshire SN10 4LD, United Kingdom</p>
  </div>
</main>

app/views/static_pages/menu.html.erb
<!-- Large banner card -->
<div id="menuCard" class="smallCard">
  <div>
    <a href="#">THE WORLD FAMOUS WILTSHIRE MENU</a>
  </div>
</div>

<section class="menu">
  <h3 id="starterMenu">Starters</h3>
    <dl>
      <dt>BAKED BRIE</dt>
      <dd>Brie cheese stuffed with raspberry coulis, golden raisins and wrapped in puff pastry. Served with a praline sauce and caramelized apples.</dd>
      <dt>BASKET OF CHIPS</dt>
      <dd>Thick cut fries, fried golden brown and served with our house dipping sauce.</dd>
      <dt>HADDOCK BITES</dt>
      <dd>Bite sized pieces of Haddock, hand battered and tossed with Thai chili sauce, Coconut milk, Cilantro and Ginger.</dd>
      <dt>HADDOCK CAKES</dt>
      <dd>Traditional Homemade fish cakes gently fried and served with fresh cut greens, grilled lemon and our homemade tartar sauce.</dd>
      <dt>PRAWN COCKTAIL</dt>
      <dd>Fresh shrimp in a pint glass served with our homemade creamy cocktail sauce and grilled lemon.</dd>
      <dt>IRISH EGG ROLLS</dt>
      <dd>Corned beef and cabbage wrapped with onions and cheddar cheese in an egg roll wrapper and fried until golden brown. Served with 1000 Island dressing.</dd>
      <dt>CHICKEN TENDERS</dt>
      <dd>Our house marinated tempura battered chicken tenders served with our homemade honey mustard sauce or tossed in one of our wing sauces for $0.50.</dd>
    </dl>
  <h3 id="sandwichMenu">Sandwiches</h3>
    <dl>
      <dt>THE ENGLISH BEEFER</dt>
      <dd>Thinly sliced roast beef with provolone cheese on a toasted baguette withwith Au Jus.</dd>
      <dt>GREEN APPLE & BRIE</dt>
      <dd>Finely sliced turkey breast with slices of brie cheese and green apple with Dijon mustard. Served on a toasted baguette.</dd>
      <dt>TANGY ROAST BEEF</dt>
      <dd>Finely sliced roast beef with horseradish mayo, cheddar cheese, fresh cut greens and tomato served on a baguette.</dd>
      <dt>CHICKEN CAESAR WRAP</dt>
      <dd>Grilled Chicken, tomatoes, parmesan, cheese, Caesar Dressing and romaine lettuce wrapped in a wheat tortilla.</dd>
      <dt>THE REUBEN</dt>
      <dd>Hand sliced corned beef topped with sauerkraut layered with Swiss cheese and 1000 island dressing served on rye bread.</dd>
      <dt>FOLKTON HADDOCK REUBEN</dt>
      <dd>Beer Battered Haddock fried golden brown and topped with Swiss cheese, Cole slaw and 1000 Island dressing. Served on a baguette.</dd>
      <dt>SMOKED CHICKEN & BRIE</dt>
      <dd>Smoked chicken breast topped with brie cheese, Dijon mustard, lettuce, and tomato. Served on a toasted baguette.</dd>
    </dl>
  <h3 id="burgerMenu">Burgers</h3>
    <dl>
      <dt>THE TERRA BURGER</dt>
      <dd>Topped with Kalamata olive,sundried tomato, pesto, roasted bell peppers leaf lettuce and feta cheese.</dd>
      <dt>THE PUB BURGER</dt>
      <dd>Half pound Sirloin burger topped with Provelone Cheese, Red Onion, Lettuce and Tomato.</dd>
      <dt>THE REUBEN BURGER</dt>
      <dd>Our certified Angus burger topped with sliced corned beef, 1000 island dressing, sauerkraut, Swiss cheese, lettuce and tomato.</dd>
      <dt>THE BULLY BURGER</dt>
      <dd>A half pound Sirloin Burger topped with an English Banger, Sauteed Mushrooms, Fried Onion Rings, Provolone Cheese, Lettuce and Tomato.</dd>
      <dt>ENGLISH RED EYE</dt>
      <dd>A half pound Sirloin Burger topped with English Bacon, Over Easy Eggs, two shots of Tabasco Sauce, Red Onions, Lettuce and Tomato.</dd>
      <dt>BLACK AND BLEU </dt>
      <dd>A half pound Sirloin Burger, blackened and topped with premium Bleu Cheese, Red Onions Lettuce and Tomato.</dd>
      <dt>TOWER OF LONDON</dt>
      <dd>A half pound sirloin burger with English bacon, English banger, HP sauce, two eggs, onion rings, sauteed mushrooms and cheddar cheese.</dd>
    </dl>
  <h3 id="dinnersMenu">Pub Dinners</h3>
    <dl>
      <dt>FISH and CHIPS</dt>
      <dd>A British Tradition; Haddock (a Royal favorite) hand battered and fried golden brown, served with chips and a side of tartar sauce.</dd>
      <dt>CHESHIRE CHICKEN</dt>
      <dd>Tender chicken breast sauteed with bacon, green onions, tomato, garlic and mushroom. Braised in our rich gravy with red wine.</dd>
      <dt>BEEF AND CHEDDAR PASTY</dt>
      <dd>Ground beef, stewed vegetables, gravy and cheese baked in a delicious puff pastry. Served with your choice of mashed potatoes, mustard mashed potatoes or chips.</dd>
      <dt>SHRIMP PUTTA</dt>
      <dd>Sauteed shrimp tossed in a puttanesca sauce and fettuccine, and served with grilled bread.</dd>
      <dt>CORNED BEEF AND CABBAGE</dt>
      <dd>Guinness steeped corned beef served with cabbage and mashed potatoes.</dd>
      <dt>GRILLED CHICKEN PESTO</dt>
      <dd>Marinated grilled chicken breast on a bed of fettuccine with pesto, sundried tomatoes, roasted bell peppers, onions and celery.</dd>
      <dt>SHRIMP & GRITS</dt>
      <dd>Plump shrimp served with Chef's specially flavored grits topped with spicy andouille sausage, vegetable trinity and tasso ham in a tomato broth.</dd>
    </dl>
  <h3 id="saladsMenu">Salads</h3>
    <dl>
      <dt>HOUSE SALAD</dt>
      <dd>Fresh greens, tomatoes, cucumbers, onions and croutons.</dd>
      <dt>SOMERSET SALAD</dt>
      <dd>Fresh greens, bleu cheese crumbles, cranberries, curried pecans and sweet red onions in a Cabernet Vinaigrette Dressing.</dd>
      <dt>CAESAR SALAD</dt>
      <dd>Crisp romaine lettuce, tomatoes, croutons and parmesan shavings with our house Caesar dressing.</dd>
      <dt>ICEBERG WEDGE SALAD</dt>
      <dd>Wedge of Iceberg lettuce, chopped bacon, bleu cheese crumbles, eggs, and tomatoes. Served with bleu cheese dressing.</dd>
    </dl>
  <h3 id="dessertsMenu">Desserts</h3>
    <dl>
      <dt>GUINNESS CHOCOLATE CAKE</dt>
      <dd>Chocolate cake made with Guinness layered in a glass with Bailey's chocolate mousse and topped with cream cheese frosting.</dd>
      <dt>BULLDOG APPLE CRISP</dt>
      <dd>Slow roasted Granny Smith apples, spiced with cinnamon, sugar, and vanilla beans, with a crumble topping and vanilla ice cream.</dd>
      <dt>CRÈME BRULEE</dt>
      <dd>Finished with fresh berries.</dd>
      <dt>BREAD & BUTTER PUDDING</dt>
      <dd>Our signature bread and butter pudding served with ice cream.</dd>
    </dl>
</section>

<nav class="sidemenu collapse">
  <ul>
    <li><a id="starters" href="#Starters">Starters</a></li>
    <li><a id="sandwiches" href="#Sandwiches">Sandwiches</a></li>
    <li><a id="burger" href="#Burgers">Burgers</a></li>
    <li><a id="dinners" href="#Dinners">Dinners</a></li>
    <li><a id="salads" href="#Salads">Salads</a></li>
    <li><a id="desserts" href="#Desserts">Desserts</a></li>
  </ul>
</nav>

app/views/static_pages/reservations.html.erb
<!-- Large banner card -->
<div id="menuCard" class="smallCard">
  <div>
    <a href="#">MAKE A RESERVATION FOR A PRIVATE ROOM</a>
  </div>
</div>

<main class="menu" id="reservationMenu">
  <h4>Wiltshire Pub is always open, but if you would like to book a private event you can do so on this page.</h4>
  <!-- Form for submitting your reservation info -->
  <form class="reservationForm">
    <div class="reservationName">
      <p>Enter your full name.</p>
    <input type="text" name="fname" placeholder="Enter Your Full Name">
    </div>
    <div class="email">
      <p>Enter your email address.</p>
      <input type="email" name="email" placeholder="Enter Your Email Address">
    </div>
    <div class="selection">
      <p>What type of event is this for?</p>
      <select name="eventType">
        <option value="party">Party</option>
        <option value="meeting">Meeting</option>
        <option value="wedding">Wedding</option>
        <option value="other">Other</option>
      </select>
    </div>
    <div class="date">
      <p>When Is your event?</p>
      <input type ="date">
    </div>
    <div class="selection">
      <p>Select your party size.</p>
      <select name="partySize">
        <option value="4-8">4-8</option>
        <option value="9-14">9-14</option>
        <option value="15+">15+</option>
      </select>
    </div>
    <div class="details">
      <p>Enter extra details here:</p>
      <textarea placeholder="Extra details" rows="4" cols="50"></textarea>
    </div>
    <div class="submitReservation" type="submit">Submit</div>
  </form> 
</main>

<div class="reservationConfirm">
  <h2>Thank you for submitting your reservation</h2>
</div>